/**
 * Stage 7 — Image Sourcing (pipeline-redesign-architecture.md).
 *
 * Fixes a confirmed production bug in agents/unsplashHero.ts (read
 * read-only for reference, not modified, not imported): its
 * buildUnsplashSearchQuery(title, notes) builds the search query mostly
 * out of the raw headline's own words (title itself is always the first
 * chunk of the query, and the "unique keyword" extraction pulls from
 * `${title}\n${notes}` combined, so headline word-soup dominates either
 * way). That produced wrong images — a toddler-and-soccer-ball photo for
 * an ASU FOOTBALL story (Unsplash's unscoped "football" defaults to
 * association football/soccer imagery worldwide, and nothing in the old
 * query disambiguated it), and an aurora photo for a meteor-shower piece
 * (loose headline/notes words like "night sky" pulling in unrelated
 * astro-adjacent stock photography with no structured anchor). The old
 * path also never captured photographer attribution, never confirmed its
 * download-trigger call actually succeeded (fire-and-forget, swallows
 * errors), and never generated alt text at all.
 *
 * NEW MODULE. STANDALONE, SHADOW MODE ONLY — not wired into
 * orchestrator.ts, newsApiSync.ts, or any hero-image call site. No
 * production file is modified.
 *
 * Live Unsplash calls are made (this stage's whole job is fetching a real
 * image) — expected. On a rate-limit/quota response (HTTP 403/429) this
 * module stops and reports that status rather than retrying.
 *
 * gpt-image-1 FALLBACK: matches the old pipeline's real, confirmed
 * behavior (agents/imageAgent.ts's generateImage — POST
 * https://api.openai.com/v1/images/generations, model: 'gpt-image-1',
 * size: '1024x1024', quality: 'medium', n: 1, response is b64_json decoded
 * to a Buffer; read-only for reference, not modified/imported). Fires only when the
 * Unsplash query ladder is genuinely exhausted with zero results across
 * every rung — a rate-limit/quota response or network error from
 * Unsplash still stops immediately without trying gpt-image-1, same as
 * before. The generation prompt is built from the same structured
 * tags/section/entity input the Unsplash query ladder already uses, never
 * the raw headline. gpt-image-1 has no photographer to credit and
 * returns raw generated bytes (base64), not a hosted URL — see
 * ImageSourcingResult's `source`/`imageBase64` fields below.
 */
import axios from 'axios';

import { config } from '../../config';
import { generateImageGemini } from '../../agents/geminiAgent';

const UNSPLASH_SEARCH = 'https://api.unsplash.com/search/photos';
const MAX_QUERY_TERMS = 5;
const QUERY_MAX_CHARS = 100;

/** Same endpoint/model/size/n/b64_json shape as agents/imageAgent.ts's generateImage — confirmed via investigation, not guessed. */
const OPENAI_IMAGES_URL = 'https://api.openai.com/v1/images/generations';
const GPT_IMAGE_MODEL = 'gpt-image-1';

// ---------------------------------------------------------------------------
// Input shape
// ---------------------------------------------------------------------------

export type ImageSourcingInput = {
  /** Structured tags — e.g. WrittenArticle.tags. Never the raw headline. */
  tags: string[];
  /** The article's section (Stage 2's output) — used for relevance ranking and disambiguation context. */
  section: string;
  /**
   * Named entity/venue the article is actually about — e.g. a fact's
   * venueName value, or a topic's subjectTag when no venue exists.
   * Highest-priority query term when present. Never the raw headline.
   */
  entity?: string;
  /** Kept only for console labeling / a last-resort alt-text fallback — never fed into the search query. */
  title: string;
};

// ---------------------------------------------------------------------------
// Disambiguation — ambiguous search terms that resolve differently
// depending on section context. Keyed by lowercase term; a rule only
// fires when the input's section matches `whenSection`. `append` adds an
// extra query word rather than replacing the original term, so the
// original term still contributes to relevance ranking.
//
// Deliberately starts minimal (just the one bug case this build spec
// concretely describes) rather than inventing untested rules for other
// ambiguous terms — extend this list as new mismatches are actually
// observed, not speculatively.
// ---------------------------------------------------------------------------

const AMBIGUOUS_TERM_RULES: { term: string; whenSection: string; append: string }[] = [
  {
    term: 'football',
    whenSection: 'sports',
    append: 'american football',
  },
  {
    term: 'turkey',
    whenSection: 'health-wellness',
    append: 'turkey tail mushroom',
  },
];

/**
 * `requiredTerms`: tokens from a fired rule's `append` phrase, EXCLUDING
 * the ambiguous `term` itself (e.g. "turkey tail mushroom" minus "turkey"
 * -> ["tail", "mushroom"]). Confirmed bug (Test A, tonight, 3rd re-run):
 * appending the disambiguation phrase changes what Unsplash returns, but
 * the picker's any-term-match kept accepting the bare ambiguous term on
 * its own, so a literal turkey photo still passed. Callers pass
 * requiredTerms into the picker so a fired rule narrows the accepted
 * match set instead of just adding to it.
 */
function applyDisambiguation(parts: string[], section: string): { parts: string[]; requiredTerms: string[] } {
  const additions: string[] = [];
  const requiredTerms: string[] = [];
  for (const part of parts) {
    const tokens = part.toLowerCase().split(/\s+/);
    for (const rule of AMBIGUOUS_TERM_RULES) {
      if (rule.whenSection !== section) continue;
      if (tokens.includes(rule.term) && !additions.includes(rule.append)) {
        additions.push(rule.append);
        const disambiguatingTokens = rule.append
          .toLowerCase()
          .split(/\s+/)
          .filter((w) => w !== rule.term.toLowerCase() && w.length >= 3);
        for (const t of disambiguatingTokens) {
          if (!requiredTerms.includes(t)) requiredTerms.push(t);
        }
      }
    }
  }
  return { parts: [...parts, ...additions], requiredTerms };
}

const STOP_TAGS = new Set(['news', 'events', 'local', 'phoenix', 'arizona']);

/**
 * Builds the Unsplash search query from structured input only — entity
 * first (most specific), then up to MAX_QUERY_TERMS tags, with
 * section-aware disambiguation applied last. Never touches input.title.
 */
export function buildImageSearchQuery(input: ImageSourcingInput): string {
  const seen = new Set<string>();
  const parts: string[] = [];

  const pushTerm = (raw: string) => {
    const term = raw.trim();
    if (!term) return;
    const key = term.toLowerCase();
    if (seen.has(key) || STOP_TAGS.has(key)) return;
    seen.add(key);
    parts.push(term);
  };

  if (input.entity) pushTerm(input.entity);
  for (const tag of input.tags) {
    if (parts.length >= MAX_QUERY_TERMS) break;
    pushTerm(tag);
  }

  if (parts.length === 0) {
    // Last-resort: section alone. Deliberately never falls back to the raw
    // title — an empty/low-signal query is a known, logged limitation, not
    // a silent revert to the exact bug this stage exists to fix.
    console.warn(`[image-sourcing] No entity/tags available for "${input.title}" — falling back to section="${input.section}" alone (low-confidence query).`);
    pushTerm(input.section);
  }

  const disambiguated = applyDisambiguation(parts, input.section);
  const query = disambiguated.parts.join(' ').slice(0, QUERY_MAX_CHARS).trim();
  return query || 'editorial';
}

function dedupeAndCleanTerms(terms: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of terms) {
    const term = raw.trim();
    if (!term) continue;
    const key = term.toLowerCase();
    if (seen.has(key) || STOP_TAGS.has(key)) continue;
    seen.add(key);
    out.push(term);
  }
  return out;
}

/**
 * Named venues/businesses (e.g. "Kähvi Coffee + Cafe") essentially never
 * appear in Unsplash's stock-photo metadata — a query built from a specific
 * entity name plus several tags is often over-specific and returns zero
 * results, discovered empirically against tests 1-4 tonight (all 4 came
 * back no-results on the entity+tags query, while a more generic query did
 * not). Rather than accept "no image" as the normal case, this builds a
 * ladder of progressively broader queries — most specific first — so
 * sourceImage() can retry with less specificity instead of giving up after
 * one narrow attempt. Each rung is still built from structured input only;
 * the raw headline never enters any rung.
 */
type QueryLadderRung = { query: string; requiredTerms: string[] };

function buildQueryLadder(input: ImageSourcingInput): QueryLadderRung[] {
  const candidates: QueryLadderRung[] = [];
  const seenQueries = new Set<string>();
  const addCandidate = (parts: string[]) => {
    const disambiguated = applyDisambiguation(parts, input.section);
    const q = disambiguated.parts.join(' ').slice(0, QUERY_MAX_CHARS).trim();
    if (q && !seenQueries.has(q)) {
      seenQueries.add(q);
      candidates.push({ query: q, requiredTerms: disambiguated.requiredTerms });
    }
  };

  // Rung 1: entity + tags — most specific (same as buildImageSearchQuery).
  const withEntity = dedupeAndCleanTerms([
    ...(input.entity ? [input.entity] : []),
    ...input.tags,
  ]).slice(0, MAX_QUERY_TERMS);
  if (withEntity.length > 0) addCandidate(withEntity);

  // Rung 2: tags only — drops the specific venue/entity name, which is the
  // term most likely to have zero matches in a general stock-photo library.
  const tagsOnly = dedupeAndCleanTerms(input.tags).slice(0, MAX_QUERY_TERMS);
  if (tagsOnly.length > 0) addCandidate(tagsOnly);

  // Rung 3: section + the single most generic tag — broad category search.
  if (input.tags.length > 0) addCandidate([input.section, input.tags[0]!]);

  // Rung 4: section alone — last resort before giving up.
  addCandidate([input.section]);

  return candidates.length > 0 ? candidates : [{ query: 'editorial', requiredTerms: [] }];
}

// ---------------------------------------------------------------------------
// Unsplash API — search, photographer capture, download-trigger, alt text
// ---------------------------------------------------------------------------

type UnsplashUser = { name?: string; links?: { html?: string } };

type UnsplashPhotoRow = {
  id?: string;
  width?: number;
  height?: number;
  urls?: { raw?: string; full?: string; regular?: string };
  links?: { download_location?: string };
  user?: UnsplashUser;
  alt_description?: string | null;
  description?: string | null;
};

type UnsplashSearchResponse = {
  results?: UnsplashPhotoRow[];
  total?: number;
  errors?: string[];
};

/** Same selection logic as unsplashHero.ts's pickHighestResolutionPhoto — ported, not imported. */
function pickHighestResolutionPhoto(results: UnsplashPhotoRow[]): UnsplashPhotoRow | null {
  if (!results.length) return null;
  let best = results[0]!;
  let bestPx = (best.width || 0) * (best.height || 0);
  for (const p of results) {
    const px = (p.width || 0) * (p.height || 0);
    if (px > bestPx) {
      bestPx = px;
      best = p;
    }
  }
  return best;
}

/** Reused as both the query-builder's word filter and the relevance-check term filter. */
const RELEVANCE_STOP_WORDS = new Set([
  'the',
  'and',
  'for',
  'with',
  'that',
  'this',
  'from',
  'are',
  'was',
  'has',
  'have',
  'will',
  'been',
  'about',
  'into',
  'your',
  'their',
]);

/**
 * Confirmed production bug (ported from unsplashHero.ts, same root cause):
 * pickHighestResolutionPhoto() ranks ALL results by resolution alone, with
 * no check that the photo has anything to do with the query — an unrelated
 * highest-resolution photo (e.g. a bird photo for a "medicinal mushrooms"
 * query) wins outright. This filters to results whose
 * alt_description/description actually mentions one of the query's
 * significant terms (stop-words and terms under 3 chars excluded) BEFORE
 * ranking by resolution. Unlike unsplashHero.ts's single-query version,
 * this is called once per ladder rung by sourceImage() below, which tries
 * every rung looking for a relevance match before ever falling back to a
 * resolution-only pick — see sourceImage()'s ladder loop.
 *
 * Confirmed follow-on bug (Test A, unsplashHero.ts, 3rd re-run — same root
 * cause applies here): appending a disambiguation term (e.g. "turkey" ->
 * "turkey tail mushroom") changes what Unsplash returns, but not what this
 * filter accepts — the bare ambiguous term stayed in queryTerms and
 * any-match logic let a mismatched photo through anyway. When the caller
 * has a fired rule's disambiguating tokens (requiredTerms — the append
 * phrase minus the ambiguous term itself), those replace queryTerms as
 * the match set entirely. Empty requiredTerms (no rule fired) keeps the
 * original any-term behavior.
 */
function pickRelevantHighestResolutionPhoto(
  results: UnsplashPhotoRow[],
  query: string,
  requiredTerms: string[] = []
): { photo: UnsplashPhotoRow | null; matchedRelevanceFilter: boolean } {
  const queryTerms = query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length >= 3 && !RELEVANCE_STOP_WORDS.has(w));

  const matchTerms = requiredTerms.length > 0 ? requiredTerms : queryTerms;

  const relevant = results.filter((p) => {
    const text = `${p.alt_description || ''} ${p.description || ''}`.toLowerCase();
    return matchTerms.some((term) => text.includes(term));
  });

  const matchedRelevanceFilter = relevant.length > 0;
  const pool = matchedRelevanceFilter ? relevant : results;
  return { photo: pickHighestResolutionPhoto(pool), matchedRelevanceFilter };
}

/**
 * Fires Unsplash's required download-trigger endpoint (Unsplash API
 * Guidelines: every time a photo is used, GET the photo's
 * `links.download_location` with your Client-ID). Unlike
 * unsplashHero.ts's fire-and-forget version, this reports whether the
 * call actually succeeded (HTTP 200) so the caller/test harness can
 * confirm it fired rather than assuming.
 */
async function triggerUnsplashDownload(
  downloadLocation: string,
  key: string
): Promise<{ fired: boolean; httpStatus?: number }> {
  if (!downloadLocation.startsWith('http')) return { fired: false };
  try {
    const res = await axios.get(downloadLocation, {
      headers: { Authorization: `Client-ID ${key}` },
      timeout: 15_000,
      validateStatus: () => true,
    });
    return { fired: res.status === 200, httpStatus: res.status };
  } catch (err: unknown) {
    console.warn('[image-sourcing] download-trigger call threw:', err instanceof Error ? err.message : String(err));
    return { fired: false };
  }
}

/**
 * Alt text sourced from Unsplash's own alt_description/description
 * (a real, factual description of the photo's actual content — exactly
 * what accessibility alt text should be), not a generic template. Only
 * falls back to a query-based generic description when Unsplash provides
 * neither field.
 */
function buildAltText(photo: UnsplashPhotoRow, query: string): string {
  const desc = (photo.alt_description || photo.description || '').trim();
  if (desc) {
    return desc.charAt(0).toUpperCase() + desc.slice(1);
  }
  return `Editorial photo related to ${query}`;
}

// ---------------------------------------------------------------------------
// Output shape
// ---------------------------------------------------------------------------

export type ImageSourcingResult = {
  query: string;
  /** Which provider actually produced this image — the real, honest answer, not an assumption. */
  source: 'unsplash' | 'gpt-image-1';
  photoId: string;
  /**
   * A real hosted URL for the unsplash path. Empty string for gpt-image-1
   * — that provider returns no URL, only raw bytes (see imageBase64).
   * Deliberately kept as a required string (not optional) so existing
   * downstream consumers of this shape don't break; an empty string is
   * falsy, so an unchanged `if (heroSource?.imageUrl)`-style check
   * safely skips rather than attempting to fetch a nonexistent URL.
   */
  imageUrl: string;
  /** Present for the gpt-image-1 path — raw generated image bytes, base64-encoded. Absent for unsplash. */
  imageBase64?: string;
  /** Real name for unsplash; 'AI-generated (gpt-image-1)' for the fallback — never stale Unsplash-shaped metadata carried over. */
  photographerName: string;
  /** Real profile URL for unsplash; empty string for gpt-image-1 (no profile to link). */
  photographerProfileUrl: string;
  altText: string;
  /** Unsplash-ToS-specific requirement — always false for gpt-image-1 (nothing to trigger). */
  downloadTriggerFired: boolean;
  /**
   * True if some rung of the query ladder actually passed the relevance
   * filter; false if every rung's results were off-topic and this result
   * is the resolution-only fallback pick. Always true for gpt-image-1
   * (generated directly from the structured input, nothing to mismatch).
   */
  matchedRelevanceFilter: boolean;
};

export type ImageSourcingOutcome =
  | { status: 'ok'; result: ImageSourcingResult }
  | { status: 'no-key' }
  /** Fires only when BOTH the Unsplash ladder AND the gpt-image-1 fallback fail. */
  | { status: 'no-image'; query: string }
  | { status: 'rate-limited'; query: string; httpStatus: number }
  | { status: 'error'; query: string; message: string };

// ---------------------------------------------------------------------------
// Stage 7 entry point
// ---------------------------------------------------------------------------

type SearchUnsplashOutcome =
  | { outcome: 'ok'; results: UnsplashPhotoRow[] }
  | { outcome: 'no-results'; httpStatus?: number }
  | { outcome: 'rate-limited'; httpStatus: number }
  | { outcome: 'error'; message: string };

async function searchUnsplashOnce(query: string, key: string): Promise<SearchUnsplashOutcome> {
  let res;
  try {
    res = await axios.get<UnsplashSearchResponse>(UNSPLASH_SEARCH, {
      params: { query, per_page: 15, orientation: 'landscape' },
      headers: { Authorization: `Client-ID ${key}` },
      timeout: 20_000,
      validateStatus: () => true,
    });
  } catch (err: unknown) {
    return { outcome: 'error', message: err instanceof Error ? err.message : String(err) };
  }

  if (res.status === 403 || res.status === 429) {
    return { outcome: 'rate-limited', httpStatus: res.status };
  }

  if (res.status !== 200 || !res.data?.results?.length) {
    return { outcome: 'no-results', httpStatus: res.status };
  }

  return { outcome: 'ok', results: res.data.results };
}

// ---------------------------------------------------------------------------
// gpt-image-1 fallback — fires only when the Unsplash ladder is genuinely
// exhausted with zero results. Same structured-input discipline as the
// Unsplash query construction: built from entity/tags/section, never the
// raw headline.
// ---------------------------------------------------------------------------

function buildImageGenerationPrompt(input: ImageSourcingInput): string {
  const subjectParts = [input.entity, ...input.tags].filter((s): s is string => Boolean(s && s.trim()));
  const subject = subjectParts.length > 0 ? subjectParts.slice(0, MAX_QUERY_TERMS).join(', ') : input.section;
  return `Photorealistic editorial photograph for a Phoenix, Arizona local lifestyle news site. Subject: ${subject}. Section: ${input.section}. No overlaid text, no watermarks, no logos.`;
}

function buildAiAltText(input: ImageSourcingInput): string {
  const subject = input.entity || input.tags[0] || input.section;
  return `AI-generated editorial image related to ${subject}`;
}

/** Same endpoint/model/size/quality/n/b64_json shape as agents/imageAgent.ts's generateImage — ported, not imported, per this file's standalone pattern. */
async function generateImageWithGptImage1(prompt: string): Promise<Buffer | null> {
  const key = config.openai.apiKey;
  if (!key) {
    console.warn('[image-sourcing] gpt-image-1 fallback skipped — OPENAI_API_KEY not set. Trying Gemini…');
    return await generateImageGemini(prompt);
  }
  try {
    const res = await axios.post(
      OPENAI_IMAGES_URL,
      { model: GPT_IMAGE_MODEL, prompt, size: '1024x1024', quality: 'medium', n: 1 },
      {
        headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
        timeout: 120_000,
        validateStatus: () => true,
      }
    );
    if (res.status >= 400) {
      const data = res.data;
      const msg =
        typeof data === 'object' && data && 'error' in (data as object)
          ? JSON.stringify((data as { error?: unknown }).error)
          : res.statusText || String(res.status);
      console.warn(`[image-sourcing] gpt-image-1 call failed: HTTP ${res.status} — ${msg}; trying Gemini…`);
      return await generateImageGemini(prompt);
    }
    const b64 = res.data?.data?.[0]?.b64_json;
    if (typeof b64 !== 'string' || !b64) {
      console.warn('[image-sourcing] gpt-image-1 response had no usable b64_json; trying Gemini…');
      return await generateImageGemini(prompt);
    }
    return Buffer.from(b64, 'base64');
  } catch (err: unknown) {
    console.warn('[image-sourcing] gpt-image-1 call threw:', err instanceof Error ? err.message : String(err), '; trying Gemini…');
    return await generateImageGemini(prompt);
  }
}

/**
 * Tries buildQueryLadder()'s rungs in order (most specific first), looking
 * for the first rung whose results actually pass the relevance filter
 * (pickRelevantHighestResolutionPhoto) — a rung with results that are all
 * off-topic no longer wins just because it's the most specific rung. Only
 * if NO rung in the whole ladder produces a relevance-filter match does
 * this fall back to a resolution-only pick, from the earliest rung that
 * had any usable results — logged clearly, same "always produce something,
 * but say so" pattern as unsplashHero.ts's plain fallback. Stops
 * immediately on a rate-limit/quota response or a network error — never
 * retries past that, per the build spec.
 */
export async function sourceImage(input: ImageSourcingInput): Promise<ImageSourcingOutcome> {
  const key = config.unsplash.accessKey;
  if (!key) {
    console.error('[image-sourcing] STOPPING — UNSPLASH_ACCESS_KEY not set. Not guessing/hardcoding a key.');
    return { status: 'no-key' };
  }

  const ladder = buildQueryLadder(input);
  console.log(`[image-sourcing] "${input.title}" → query ladder: ${JSON.stringify(ladder)}`);

  let query = ladder[0]!.query;
  let photo: UnsplashPhotoRow | null = null;
  let matchedRelevanceFilter = false;
  let fallback: { query: string; photo: UnsplashPhotoRow } | null = null;

  for (const candidate of ladder) {
    const attempt = await searchUnsplashOnce(candidate.query, key);
    if (attempt.outcome === 'rate-limited') {
      console.error(`[image-sourcing] STOPPING — Unsplash rate-limit/quota response (HTTP ${attempt.httpStatus}). Not retrying.`);
      return { status: 'rate-limited', query: candidate.query, httpStatus: attempt.httpStatus! };
    }
    if (attempt.outcome === 'error') {
      console.error(`[image-sourcing] Unsplash search call threw: ${attempt.message}`);
      return { status: 'error', query: candidate.query, message: attempt.message! };
    }
    if (attempt.outcome === 'no-results') {
      console.log(`[image-sourcing] rung "${candidate.query}" → no results, trying next rung if any`);
      continue;
    }

    const picked = pickRelevantHighestResolutionPhoto(attempt.results, candidate.query, candidate.requiredTerms);
    if (!picked.photo?.urls) {
      console.log(`[image-sourcing] rung "${candidate.query}" → results had no usable photo URLs, trying next rung if any`);
      continue;
    }
    if (!fallback) {
      fallback = { query: candidate.query, photo: picked.photo };
    }
    if (picked.matchedRelevanceFilter) {
      query = candidate.query;
      photo = picked.photo;
      matchedRelevanceFilter = true;
      console.log(`[image-sourcing] rung "${candidate.query}" → matched (relevance filter satisfied)`);
      break;
    }
    console.log(`[image-sourcing] rung "${candidate.query}" → results found but none matched the relevance filter, trying next rung if any`);
  }

  if (!photo && fallback) {
    console.warn(
      `[image-sourcing] No rung in the ladder produced a relevance-filter match. Falling back to resolution-only pick from rung "${fallback.query}" (ladder tried: ${JSON.stringify(ladder)}).`
    );
    query = fallback.query;
    photo = fallback.photo;
  }

  // Confirmed bug (Ketel Marte casino articles, this morning): this used
  // to be `if (!photo)` only — a rung with results but zero relevance
  // matches still set `photo` from the resolution-only fallback above,
  // so gpt-image-1 was never tried and a mismatched photo (three women
  // running, for a "sports" query with no relevant results) got used
  // silently. Now triggers on EITHER a genuinely empty ladder (photo still
  // null) OR a ladder that returned photos but never a relevance match.
  if (!photo || !matchedRelevanceFilter) {
    const reason = !photo
      ? 'Exhausted query ladder with no results'
      : 'No rung produced a relevance-filter match (best available was a resolution-only pick)';
    console.warn(`[image-sourcing] ${reason}. Ladder tried: ${JSON.stringify(ladder)} — trying gpt-image-1.`);

    const genPrompt = buildImageGenerationPrompt(input);
    const genBuffer = await generateImageWithGptImage1(genPrompt);
    if (genBuffer) {
      const result: ImageSourcingResult = {
        query: genPrompt,
        source: 'gpt-image-1',
        photoId: `gpt-image-1-${Date.now()}`,
        imageUrl: '',
        imageBase64: genBuffer.toString('base64'),
        photographerName: 'AI-generated (gpt-image-1)',
        photographerProfileUrl: '',
        altText: buildAiAltText(input),
        downloadTriggerFired: false,
        matchedRelevanceFilter: true,
      };
      console.log(`[image-sourcing] gpt-image-1 fallback succeeded — generated ${genBuffer.length} bytes.`);
      return { status: 'ok', result };
    }

    if (!photo) {
      console.warn('[image-sourcing] gpt-image-1 fallback also failed — no image available from any source.');
      return { status: 'no-image', query };
    }
    console.warn('[image-sourcing] gpt-image-1 fallback also failed — using the irrelevant resolution-only Unsplash pick as last resort.');
  }

  const imageUrl = photo.urls?.raw || photo.urls?.full || photo.urls?.regular || '';

  let downloadTriggerFired = false;
  const downloadLoc = photo.links?.download_location;
  if (downloadLoc) {
    const trig = await triggerUnsplashDownload(downloadLoc, key);
    downloadTriggerFired = trig.fired;
    console.log(`[image-sourcing] download-trigger call → fired=${trig.fired}, httpStatus=${trig.httpStatus ?? '(threw)'}`);
  } else {
    console.warn('[image-sourcing] Selected photo has no links.download_location — cannot fire required download-trigger call.');
  }

  const result: ImageSourcingResult = {
    query,
    source: 'unsplash',
    photoId: photo.id || '(unknown)',
    imageUrl,
    photographerName: photo.user?.name || '(unknown photographer)',
    photographerProfileUrl: photo.user?.links?.html || '',
    altText: buildAltText(photo, query),
    downloadTriggerFired,
    matchedRelevanceFilter,
  };

  console.log(
    `[image-sourcing] selected photoId=${result.photoId} photographer="${result.photographerName}" downloadTriggerFired=${downloadTriggerFired} matchedRelevanceFilter=${matchedRelevanceFilter}`
  );
  return { status: 'ok', result };
}

// ---------------------------------------------------------------------------
// Test harness — chains real Stage 4 (sufficiencyGate) → Stage 5
// (articleWriter) to get real WrittenArticle.tags for tests 1-4 (same
// fixtures used for Stage 5/6 tonight), then runs this stage on the
// resulting tags/section/entity. writeArticle()/evaluateSufficiency() are
// dynamic-imported here, test-harness-only, same pattern as
// verificationGate.ts's harness. Adds one BONUS fixture specifically
// constructed to exercise the football/sports disambiguation rule, since
// none of tests 1-4 happen to contain that term.
// ---------------------------------------------------------------------------

type HarnessTopicInput = {
  title: string;
  snippet?: string;
  section?: string;
  verdict?: string;
  subjectTag?: string;
  [key: string]: unknown;
};

type HarnessFact = { field: string; value: string; source: string; sourceUrl?: string };

type HarnessSourceGatheringResult = {
  topic: HarnessTopicInput;
  facts: HarnessFact[];
  primarySourceFound: boolean;
  factCount: number;
};

function extractEntity(sourcing: HarnessSourceGatheringResult): string | undefined {
  const venueFact = sourcing.facts.find((f) => f.field === 'venueName');
  if (venueFact) return venueFact.value;
  return sourcing.topic.subjectTag;
}

async function runTestHarness(): Promise<void> {
  const { writeArticle } = await import('./articleWriter');
  const { evaluateSufficiency } = await import('./sufficiencyGate');

  type Case = { label: string; topic: HarnessTopicInput; sourcing: HarnessSourceGatheringResult };

  const cases: Case[] = [
    {
      label: 'TEST 1: WordCamp US 2026 (rich facts)',
      topic: { title: 'WordCamp US 2026', section: 'news', subjectTag: 'conference', verdict: 'direct-local' },
      sourcing: {
        topic: { title: 'WordCamp US 2026', section: 'news', subjectTag: 'conference', verdict: 'direct-local' },
        facts: [
          { field: 'venueName', value: 'Phoenix Convention Center North', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/wordcamp' },
          { field: 'address', value: '100 N 3rd St, Phoenix, AZ 85004', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/wordcamp' },
          { field: 'date', value: '2026-08-16', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/wordcamp' },
          { field: 'time', value: '9:00 AM', source: 'venue page — HTTP fetch (https://2026.us.wordcamp.org/)', sourceUrl: 'https://2026.us.wordcamp.org/' },
          { field: 'ticketUrl', value: 'https://2026.us.wordcamp.org/tickets/', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/wordcamp' },
          { field: 'price', value: '$85', source: 'venue page — HTTP fetch (https://2026.us.wordcamp.org/)', sourceUrl: 'https://2026.us.wordcamp.org/' },
          { field: 'description', value: 'WordCamp US brings together WordPress users, developers, and businesses for three days of sessions and workshops.', source: 'venue page — HTTP fetch (https://2026.us.wordcamp.org/)', sourceUrl: 'https://2026.us.wordcamp.org/' },
        ],
        primarySourceFound: true,
        factCount: 7,
      },
    },
    {
      label: 'TEST 2: Sunday Yoga (thin facts)',
      topic: { title: 'Sunday Yoga', section: 'health-wellness', subjectTag: 'yoga class', verdict: 'direct-local' },
      sourcing: {
        topic: { title: 'Sunday Yoga', section: 'health-wellness', subjectTag: 'yoga class', verdict: 'direct-local' },
        facts: [
          { field: 'venueName', value: 'Kähvi Coffee + Cafe', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/sundayyoga' },
        ],
        primarySourceFound: false,
        factCount: 1,
      },
    },
    {
      label: 'TEST 3: Rare Meteor Shower (national-reframe)',
      topic: { title: 'Rare Meteor Shower Peaks Tonight', section: 'news', subjectTag: 'astronomy', verdict: 'national-reframe' },
      sourcing: {
        topic: { title: 'Rare Meteor Shower Peaks Tonight', section: 'news', subjectTag: 'astronomy', verdict: 'national-reframe' },
        facts: [
          { field: 'visibility', value: 'Not visible from Arizona tonight due to forecast monsoon cloud cover', source: 'National Weather Service Phoenix', sourceUrl: 'https://weather.gov/psr/forecast' },
          { field: 'alternative', value: 'Best alternative Arizona viewing window is Thursday night, when skies are forecast to clear', source: 'National Weather Service Phoenix', sourceUrl: 'https://weather.gov/psr/forecast' },
          { field: 'date', value: '2026-08-13', source: 'American Meteor Society', sourceUrl: 'https://amsmeteors.org' },
          { field: 'description', value: 'The Perseid meteor shower peaks tonight with up to 60 meteors per hour visible under clear skies.', source: 'American Meteor Society', sourceUrl: 'https://amsmeteors.org' },
        ],
        primarySourceFound: true,
        factCount: 4,
      },
    },
    {
      label: 'TEST 4: Trivia Night (conflicting facts)',
      topic: { title: 'Trivia Night at Arizona Wilderness Brewing Co.', section: 'nightlife', subjectTag: 'trivia', verdict: 'direct-local' },
      sourcing: {
        topic: { title: 'Trivia Night at Arizona Wilderness Brewing Co.', section: 'nightlife', subjectTag: 'trivia', verdict: 'direct-local' },
        facts: [
          { field: 'venueName', value: 'Arizona Wilderness Brewing Co.', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/trivia' },
          { field: 'date', value: 'Wednesdays', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/trivia' },
          { field: 'price', value: 'Free', source: 'SerpAPI Events', sourceUrl: 'https://serpapi.example/trivia' },
          { field: 'price', value: '$5 buy-in', source: 'venue page — HTTP fetch (https://azwbeer.com/gilbert/events/)', sourceUrl: 'https://azwbeer.com/gilbert/events/' },
        ],
        primarySourceFound: true,
        factCount: 4,
      },
    },
  ];

  console.log('[image-sourcing] ========== TEST HARNESS start ==========');

  const summary: { label: string; outcome: ImageSourcingOutcome }[] = [];

  for (const c of cases) {
    console.log(`\n\n=== ${c.label} ===`);
    const sufficiency = evaluateSufficiency(c.sourcing);
    const article = await writeArticle(c.topic, c.sourcing, sufficiency);
    if (!article) {
      console.log('(no article written — decision was skip; nothing to source an image for)');
      continue;
    }
    console.log(`Stage 5 tags: ${JSON.stringify(article.tags)}`);

    const input: ImageSourcingInput = {
      tags: article.tags,
      section: c.topic.section || 'news',
      entity: extractEntity(c.sourcing),
      title: article.title,
    };
    console.log(`Image sourcing input: entity=${JSON.stringify(input.entity)}, section=${input.section}`);

    const outcome = await sourceImage(input);
    summary.push({ label: c.label, outcome });
    console.log('Outcome:');
    console.log(JSON.stringify(outcome, null, 2));
  }

  console.log('\n\n=== BONUS: football/sports disambiguation rule ===');
  const bonusInput: ImageSourcingInput = {
    tags: ['football', 'college football', 'ASU Sun Devils'],
    section: 'sports',
    entity: 'ASU Sun Devils',
    title: 'ASU Football Season Opener Set for This Weekend',
  };
  console.log(`Query built: "${buildImageSearchQuery(bonusInput)}" (confirms "american football" was appended)`);
  const bonusOutcome = await sourceImage(bonusInput);
  summary.push({ label: 'BONUS: football/sports disambiguation', outcome: bonusOutcome });
  console.log('Outcome:');
  console.log(JSON.stringify(bonusOutcome, null, 2));

  console.log('\n\n=== FORCED: gpt-image-1 fallback ===');
  console.log('(Nonsense query terms alone did NOT reliably force zero Unsplash results — Unsplash\'s search degrades gracefully and returned a loosely-related photo instead of a hard empty set. Forcing this deterministically instead by intercepting the Unsplash HTTP call itself for the duration of this one test — same monkey-patch pattern articleWriter.ts\'s own test harness already uses to prove a call did NOT happen. The real gpt-image-1 call and the real Sanity upload below are NOT intercepted — those are genuine.)');
  const forcedInput: ImageSourcingInput = {
    tags: ['forced fallback test tag'],
    section: 'news',
    entity: 'Forced Fallback Test Entity',
    title: 'Forced gpt-image-1 fallback test',
  };
  const realAxiosGet = axios.get;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (axios as any).get = async (url: string, opts: unknown) => {
    if (typeof url === 'string' && url.startsWith(UNSPLASH_SEARCH)) {
      return { status: 200, data: { results: [] }, headers: {} };
    }
    return realAxiosGet(url, opts as never);
  };
  let forcedOutcome: ImageSourcingOutcome;
  try {
    forcedOutcome = await sourceImage(forcedInput);
  } finally {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (axios as any).get = realAxiosGet;
  }
  summary.push({ label: 'FORCED: gpt-image-1 fallback', outcome: forcedOutcome });
  console.log('Outcome (imageBase64 omitted from this printout — logged separately below):');
  console.log(
    JSON.stringify(
      forcedOutcome,
      (key, value) => (key === 'imageBase64' && typeof value === 'string' ? `[${value.length} base64 chars omitted]` : value),
      2
    )
  );

  if (forcedOutcome.status === 'ok' && forcedOutcome.result.source === 'gpt-image-1' && forcedOutcome.result.imageBase64) {
    console.log('\nConfirmed: source="gpt-image-1", real image bytes present. Proving "attached" with a real Sanity asset upload (read/write reuse of the existing, unmodified uploadImageBufferToSanity — not a modification to that file):');
    try {
      const { uploadImageBufferToSanity } = await import('../../agents/sanityPublisher');
      const buf = Buffer.from(forcedOutcome.result.imageBase64, 'base64');
      const assetId = await uploadImageBufferToSanity(buf, `test-gpt-image-1-fallback-${Date.now()}.png`);
      console.log(`ATTACHED — real Sanity image asset created: ${assetId} (${buf.length} bytes)`);
    } catch (err: unknown) {
      console.error('Sanity asset upload failed:', err instanceof Error ? err.message : String(err));
    }
  } else {
    console.error(`UNEXPECTED — forced test did not produce a gpt-image-1 result: ${JSON.stringify({ status: forcedOutcome.status, source: forcedOutcome.status === 'ok' ? forcedOutcome.result.source : undefined })}`);
  }

  console.log('\n\n########## IMAGE SOURCING TEST HARNESS SUMMARY ##########');
  for (const { label, outcome } of summary) {
    if (outcome.status === 'ok') {
      console.log(
        `${label} → OK — source=${outcome.result.source}, query="${outcome.result.query}", photographer="${outcome.result.photographerName}", downloadTriggerFired=${outcome.result.downloadTriggerFired}`
      );
    } else {
      console.log(`${label} → ${outcome.status.toUpperCase()}${'query' in outcome ? ` (query="${outcome.query}")` : ''}`);
    }
  }
  console.log('[image-sourcing] ========== TEST HARNESS end ==========');
}

function safeErrorSummary(err: unknown): string {
  if (axios.isAxiosError(err)) {
    const status = err.response?.status;
    const body = err.response?.data;
    const apiMessage =
      body && typeof body === 'object' && 'error' in (body as Record<string, unknown>)
        ? JSON.stringify((body as Record<string, unknown>).error)
        : undefined;
    return `AxiosError: HTTP ${status ?? '(no response)'}${apiMessage ? ` — ${apiMessage}` : ` — ${err.message}`}`;
  }
  if (err instanceof Error) return `${err.name}: ${err.message}`;
  return String(err);
}

if (require.main === module) {
  runTestHarness().catch((err) => {
    console.error('[image-sourcing] Fatal:', safeErrorSummary(err));
    process.exit(1);
  });
}
